CREATE DATABASE CinemaManagement;
GO

USE CinemaManagement;
GO

CREATE TABLE Movies (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    ReleaseDate DATETIME2 NOT NULL,
    Genre NVARCHAR(100) NOT NULL
);

CREATE TABLE CinemaLocations (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    City NVARCHAR(100) NOT NULL,
    CinemaAddress NVARCHAR(100) NOT NULL
);

CREATE TABLE Rooms (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CinemaLocationId UNIQUEIDENTIFIER NOT NULL,
    RoomName NVARCHAR(30) NOT NULL,
    FOREIGN KEY (CinemaLocationId) REFERENCES CinemaLocations(Id) ON DELETE CASCADE
);

CREATE TABLE Seats (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    RoomId UNIQUEIDENTIFIER NOT NULL,
    SeatType NVARCHAR(15) NOT NULL,
    SeatRow INT NOT NULL,
    SeatColumn INT NOT NULL,
    FOREIGN KEY (RoomId) REFERENCES Rooms(Id) ON DELETE CASCADE
);

CREATE TABLE Projections (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    MovieId UNIQUEIDENTIFIER NOT NULL,
    RoomId UNIQUEIDENTIFIER NOT NULL,
    ProjectionTime DATETIME2 NOT NULL,
    TicketPrice DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (MovieId) REFERENCES Movies(Id) ON DELETE CASCADE,
    FOREIGN KEY (RoomId) REFERENCES Rooms(Id) ON DELETE CASCADE
);

CREATE TABLE Tickets (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ProjectionId UNIQUEIDENTIFIER NOT NULL,
    PurchaseTime DATETIME2 NOT NULL DEFAULT GETDATE(),
    SeatId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (ProjectionId) REFERENCES Projections(Id) ON DELETE CASCADE,
    FOREIGN KEY (SeatId) REFERENCES Seats(Id) ON DELETE NO ACTION
);